# Generated by Django 5.2 on 2026-01-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_etudiant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='sync_fix',
            field=models.BooleanField(default=True),
        ),
    ]
