# Generated by Django 5.2 on 2026-01-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_etudiant_app', '0002_sessionyearmodel_sync_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='last_sync_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
