# Generated by Django 5.2 on 2026-01-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_etudiant_app', '0003_inscription_last_sync_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='releve_notes',
            field=models.FileField(blank=True, null=True, upload_to='releves/'),
        ),
    ]
