# Generated by Django 5.2 on 2026-01-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_etudiant_app', '0004_inscription_statut_alter_inscription_releve_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
