# Generated by Django 5.2 on 2026-01-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_etudiant_app', '0005_alter_inscription_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='frais_base',
            field=models.IntegerField(default=60000, help_text="Frais d'inscription de base pour ce niveau"),
        ),
    ]
